Repository goauthentik/authentik, pull requests merged in 2025-02, with the labels that each got.

#13025 web: Silence ESBuild warning.
  web/build.mjs
Labels: bug, bug/confirmed

#12771 web/admin: update Application Wizard button placement
  web/src/admin/applications/ApplicationForm.ts
  web/src/admin/applications/ApplicationListPage.ts
  web/src/admin/applications/wizard/ApplicationWizardStep.ts
  web/src/user/LibraryPage/ak-library-application-empty-list.ts
  web/tests/specs/new-application-by-wizard.ts
Labels: deploy_me

#12733 web: Indicate when caps-lock is active during password input.
  web/src/common/styles/authentik.css
  web/src/elements/utils/focus.ts
  web/src/flow/components/ak-flow-password-input.ts
Labels: javascript, enhancement/confirmed

#13281 website/docs: Fix Docusaurus plugin regression in Algolia search
  website/package-lock.json
  website/package.json
Labels: javascript, bug/confirmed

#13026 web: ESBuild performance + Live reload
  web/build-observer-plugin.mjs
  web/build.mjs
  web/package-lock.json
  web/package.json
  web/src/admin/AdminInterface/AdminInterface.ts
  web/src/common/client.ts
  web/src/flow/FlowInterface.ts
  web/src/user/UserInterface.ts
Labels: enhancement, javascript
