Repository goauthentik/authentik, pull requests merged in 2025-04, with the labels that each got.

#13684 website/integrations: add certificate instructions to apache guacamole
  website/integrations/services/apache-guacamole/index.mdx
Labels: documentation

#13675 website/integrations: add sidero omni
  website/integrations/services/omni/index.md
  website/sidebarsIntegrations.js
Labels: documentation

#13687 website/docs: add log levels section to logs documentation
  website/docs/troubleshooting/logs.md
  website/docs/troubleshooting/logs.mdx
Labels: documentation

#13766 web: Fix TypeScript compilation issues for mixins, events.
  web/src/admin/AdminInterface/AboutModal.ts
  web/src/admin/applications/ApplicationListPage.ts
  web/src/admin/groups/RelatedUserList.ts
  web/src/admin/users/UserListPage.ts
  web/src/elements/Interface/authentikConfigProvider.ts
  web/src/elements/Interface/brandProvider.ts
  web/src/elements/Interface/capabilitiesProvider.ts
  web/src/elements/Interface/licenseSummaryProvider.ts
  web/src/elements/Interface/versionProvider.ts
  web/src/elements/ak-dual-select/types.ts
  web/src/elements/types.ts
  web/src/elements/utils/customEvents.ts
  web/src/elements/utils/eventEmitter.ts
Labels: enhancement

#13755 web: Tidy temporal utilities.
  web/src/admin/admin-overview/cards/RecentEventsCard.ts
  web/src/admin/blueprints/BlueprintListPage.ts
  web/src/admin/enterprise/EnterpriseLicenseListPage.ts
  web/src/admin/events/EventListPage.ts
  web/src/admin/events/EventViewPage.ts
  web/src/admin/groups/MemberSelectModal.ts
  web/src/admin/groups/RelatedUserList.ts
  web/src/admin/outposts/OutpostHealth.ts
  web/src/admin/outposts/OutpostHealthSimple.ts
  web/src/admin/policies/reputation/ReputationListPage.ts
  web/src/admin/stages/invitation/InvitationForm.ts
  web/src/admin/system-tasks/SystemTaskListPage.ts
  web/src/admin/tokens/TokenForm.ts
  web/src/admin/tokens/TokenListPage.ts
  web/src/admin/users/ServiceAccountForm.ts
  web/src/admin/users/UserDevicesTable.ts
  web/src/admin/users/UserListPage.ts
  web/src/admin/users/UserViewPage.ts
  web/src/common/temporal.ts
  web/src/common/utils.ts
  web/src/components/events/ObjectChangelog.ts
  web/src/components/events/UserEvents.ts
  web/src/elements/charts/Chart.ts
  web/src/elements/events/LogViewer.ts
  web/src/elements/forms/Form.ts
  web/src/elements/notifications/APIDrawer.ts
  web/src/elements/notifications/NotificationDrawer.ts
  web/src/elements/oauth/UserAccessTokenList.ts
  web/src/elements/oauth/UserRefreshTokenList.ts
  web/src/elements/sync/SyncStatusCard.ts
  web/src/elements/user/SessionList.ts
  web/src/elements/user/UserConsentList.ts
  web/src/elements/user/UserReputationList.ts
  web/src/user/user-settings/mfa/MFADevicesPage.ts
  web/src/user/user-settings/tokens/UserTokenForm.ts
  web/src/user/user-settings/tokens/UserTokenList.ts
Labels: enhancement

#12661 sources/ldap: lookup group memberships from user attribute
  authentik/sources/ldap/api.py
  authentik/sources/ldap/migrations/0007_ldapsource_lookup_groups_from_user.py
  authentik/sources/ldap/models.py
  authentik/sources/ldap/sync/membership.py
  authentik/sources/ldap/tests/mock_freeipa.py
  authentik/sources/ldap/tests/test_sync.py
  blueprints/schema.json
  schema.yml
  web/src/admin/sources/ldap/LDAPSourceForm.ts
Labels: status/reviewing

#13962 website: Port WWW theme to docs site. Prep for package.
  website/docusaurus.config.ts
  website/package-lock.json
  website/package.json
  website/src/css/custom.css
  website/static/fonts/RedHatFont-updated/RedHatMono/RedHatMono-updated-Bold.woff2
  website/static/fonts/RedHatFont-updated/RedHatMono/RedHatMono-updated-BoldItalic.woff2
  website/static/fonts/RedHatFont-updated/RedHatMono/RedHatMono-updated-Italic.woff2
  website/static/fonts/RedHatFont-updated/RedHatMono/RedHatMono-updated-Light.woff2
  website/static/fonts/RedHatFont-updated/RedHatMono/RedHatMono-updated-LightItalic.woff2
  website/static/fonts/RedHatFont-updated/RedHatMono/RedHatMono-updated-Medium.woff2
  website/static/fonts/RedHatFont-updated/RedHatMono/RedHatMono-updated-MediumItalic.woff2
  website/static/fonts/RedHatFont-updated/RedHatMono/RedHatMono-updated-Regular.woff2
  website/static/fonts/RedHatFont-updated/RedHatMono/RedHatMonoVF-updated-Italic.woff2
  website/static/fonts/RedHatFont-updated/RedHatMono/RedHatMonoVF-updated.woff2
  website/static/fonts/RedHatFont-updated/modified/RedHatDisplayVF-updated-ItalicModified.woff2
  website/static/fonts/RedHatFont-updated/modified/RedHatDisplayVFModified-updated.woff2
  website/static/fonts/RedHatFont-updated/modified/RedHatTextVF-updated-ItalicModified.woff2
  website/static/fonts/RedHatFont-updated/modified/RedHatTextVFModified-updated.woff2
Labels: enhancement
