Repository goauthentik/authentik, pull requests merged in 2025-03, with the labels that each got.

#13391 website: add a better edit this page element
  website/docusaurus.config.ts
  website/src/theme/EditMetaRow/index.tsx
  website/src/theme/EditMetaRow/styles.module.css
  website/src/theme/EditThisPage/index.tsx
Labels: documentation, enhancement

#13454 web: Ignore Storybook when running codespell.
  pyproject.toml
Labels: bug

#13319 website/docs: Apple Business Manager Integration.
  web/src/admin/providers/ssf/SSFProviderFormPage.ts
  website/docs/add-secure-apps/applications/manage_apps.mdx
  website/docs/add-secure-apps/providers/ssf/create-ssf-provider.md
  website/docusaurus.config.ts
  website/integrations/services/apple/index.md
  website/sidebarsIntegrations.js
  website/src/css/custom.css
Labels: documentation, enhancement

#13379 web: Fix inline documentation rendering
  package-lock.json
  web/.storybook/main.ts
  web/eslint.config.mjs
  web/package-lock.json
  web/package.json
  web/scripts/build-web.mjs
  web/scripts/esbuild/build-mdx-plugin.mjs
  web/scripts/esbuild/build-observer-plugin.mjs
  web/scripts/esbuild/remark/remark-admonition.mjs
  web/scripts/esbuild/remark/remark-headings.mjs
  web/scripts/esbuild/remark/remark-links.mjs
  web/scripts/esbuild/remark/remark-lists.mjs
  web/src/admin/applications/ApplicationListPage.ts
  web/src/admin/providers/oauth2/OAuth2ProviderViewPage.ts
  web/src/admin/providers/proxy/ProxyProviderViewPage.ts
  web/src/admin/providers/scim/SCIMProviderViewPage.ts
  web/src/admin/providers/ssf/SSFProviderViewPage.ts
  web/src/admin/sources/kerberos/KerberosSourceViewPage.ts
  web/src/common/styles/authentik.css
  web/src/common/styles/one-dark.css
  web/src/common/styles/theme-dark.css
  web/src/elements/Base.ts
  web/src/elements/Markdown.ts
  web/src/global.d.ts
  website/docs/add-secure-apps/providers/oauth2/index.mdx
  website/src/css/custom.css
Labels: documentation, bug/confirmed

#13610 web: Client-side MDX rendering
  web/.prettierrc.json
  web/package-lock.json
  web/package.json
  web/scripts/build-web.mjs
  web/scripts/esbuild/build-mdx-plugin.mjs
  web/scripts/esbuild/remark/remark-links.mjs
  web/src/admin/admin-settings/AdminSettingsPage.ts
  web/src/admin/applications/ApplicationListPage.ts
  web/src/admin/providers/google_workspace/GoogleWorkspaceProviderViewPage.ts
  web/src/admin/providers/microsoft_entra/MicrosoftEntraProviderViewPage.ts
  web/src/admin/providers/oauth2/OAuth2ProviderViewPage.ts
  web/src/admin/providers/proxy/ProxyProviderViewPage.ts
  web/src/admin/providers/scim/SCIMProviderViewPage.ts
  web/src/admin/providers/ssf/SSFProviderViewPage.ts
  web/src/admin/sources/kerberos/KerberosSourceViewPage.ts
  web/src/common/sentry.ts
  web/src/common/styles/authentik.css
  web/src/elements/Markdown.ts
  web/src/elements/ak-mdx/MDXModuleContext.ts
  web/src/elements/ak-mdx/ak-mdx.tsx
  web/src/elements/ak-mdx/components/MDXAnchor.tsx
  web/src/elements/ak-mdx/components/MDXWrapper.tsx
  web/src/elements/ak-mdx/index.ts
  web/src/elements/ak-mdx/remark/remark-admonition.ts
  web/src/elements/ak-mdx/remark/remark-headings.ts
  web/src/elements/ak-mdx/remark/remark-lists.ts
  web/src/global.d.ts
  web/tsconfig.base.json
Labels: bug, enhancement

#13619 website/docs: Flesh out integrations copy changes.
  website/integrations/index.mdx
  website/integrations/services/index.mdx
Labels: documentation

#13586 website/docs: Clarify frontend development. Document local overrides.
  authentik/lib/default.yml
  scripts/generate_config.py
  website/docs/developer-docs/setup/frontend-dev-environment.md
  website/docs/developer-docs/setup/full-dev-environment.mdx
  website/docs/developer-docs/setup/website-dev-environment.md
  website/docs/install-config/install/docker-compose.mdx
Labels: documentation
