Repository goauthentik/authentik, pull requests merged in 2025-09, with the labels that each got.

#16502 website/integrations: bitwarden: fix ent notice
  website/integrations/security/bitwarden/index.mdx
Labels: backport/version-2025.8

#16286 root: clean up README
  CONTRIBUTING.md
  README.md
Labels: backport/version-2025.8

#16576 website/docs: remove base providers redirect.
  website/docs/static/_redirects
Labels: backport/version-2025.8

#16584 core: bump django from 5.1.11 to v5.1.12
  pyproject.toml
  uv.lock
Labels: backport/version-2025.8

#16589 website: Update license text to use "directory"
  website/LICENSE
Labels: backport/version-2025.8

#16696 website/docs: clarify docker compose install
  website/docs/install-config/install/docker-compose.mdx
Labels: backport/version-2025.8

#16456 sources/oauth/entra_id: do not assume group_id comes from entra
  authentik/sources/oauth/types/entra_id.py
Labels: backport/version-2025.8

#16579 stages/email_authenticator: Fix email mfa loop
  authentik/stages/authenticator_email/stage.py
  authentik/stages/authenticator_email/tests.py
Labels: backport/version-2025.8

#16809 website/docs: 2025.8.3 release notes
  website/docs/releases/2025/v2025.8.mdx
Labels: backport/version-2025.8

#16779 webiste/docs: improve user ref doc
  website/docs/users-sources/user/user_ref.mdx
Labels: backport/version-2025.8

#16834 core: bump zope-interface from 7.2 to v8.0
  uv.lock
Labels: dependencies

#16832 core: bump trio from 0.30.0 to v0.31.0
  uv.lock
Labels: dependencies

#16831 core: bump pyparsing from 3.2.3 to v3.2.4
  uv.lock
Labels: dependencies

#16830 core: bump pynacl from 1.5.0 to v1.6.0
  uv.lock
Labels: dependencies

#16827 core: bump opentelemetry-api from 1.36.0 to v1.37.0
  uv.lock
Labels: dependencies

#16825 core: bump microsoft-kiota-serialization-text from 1.9.5 to v1.9.7
  uv.lock
Labels: dependencies

#16824 core: bump microsoft-kiota-serialization-multipart from 1.9.5 to v1.9.7
  uv.lock
Labels: dependencies

#16821 core: bump microsoft-kiota-http from 1.9.5 to v1.9.6
  uv.lock
Labels: dependencies

#16818 core: bump jsonschema-specifications from 2025.4.1 to v2025.9.1
  uv.lock
Labels: dependencies

#16817 core: bump jsii from 1.113.0 to v1.114.1
  uv.lock
Labels: dependencies

#16816 core: bump httplib2 from 0.22.0 to v0.31.0
  uv.lock
Labels: dependencies

#16815 core: bump dnspython from 2.7.0 to v2.8.0
  uv.lock
Labels: dependencies

#16465 providers/scim: fix string formatting for SCIM user filter
  authentik/providers/scim/clients/users.py
Labels: backport/version-2025.8

#16918 providers/ldap: add include_children parameter to cached search mode
  internal/outpost/ldap/search/memory/memory.go
Labels: backport/version-2025.8

#17005 lib/config: fix listen settings
  authentik/lib/debug.py
  authentik/lib/default.yml
  authentik/tasks/forks.py
  internal/config/struct.go
Labels: backport/version-2025.8

#17009 tasks: fix logger name
  authentik/outposts/controllers/kubernetes.py
  authentik/tasks/middleware.py
Labels: backport/version-2025.8

#17069 web/admin: fix federation sources automatically selected
  web/src/admin/providers/oauth2/OAuth2ProvidersProvider.ts
  web/src/admin/providers/oauth2/OAuth2Sources.ts
Labels: backport/version-2025.8, area:frontend

#17068 enterprise/stages/mtls: Improve Email address extraction
  authentik/crypto/models.py
  authentik/enterprise/stages/mtls/stage.py
  internal/outpost/flow/executor.go
Labels: area:backend

#16752 web: Fix layout class for 'row' in LibraryPage
  web/src/user/LibraryPage/ak-library-application-list.ts
Labels: backport/version-2025.8

#17015 rbac: optimize rbac assigned by users query
  authentik/rbac/api/rbac_assigned_by_users.py
Labels: backport/version-2025.8

#17093 cmd/server/healthcheck: info log success instead of debug
  cmd/server/healthcheck.go
Labels: backport/version-2025.8

#17100 providers/oauth2: fix authentication error with identical app passwords
  authentik/providers/oauth2/tests/test_token_cc_user_pw.py
  authentik/providers/oauth2/views/token.py
Labels: backport/version-2025.8

#17119 website/docs: 2025.8.4 release notes
  website/docs/releases/2025/v2025.8.mdx
Labels: backport/version-2025.8

#17137 website/docs: developer docs: adjust sentence for writing docs
  website/docs/developer-docs/docs/writing-documentation.md
Labels: backport/version-2025.8
