Repository goauthentik/authentik, pull requests merged in 2025-10, with the labels that each got.

#17188 core: bump markupsafe from 3.0.2 to v3.0.3
  uv.lock
Labels: dependencies

#17191 core: bump msal from 1.33.0 to v1.34.0
  uv.lock
Labels: dependencies

#17195 core: bump txaio from 25.6.1 to v25.9.2
  uv.lock
Labels: dependencies

#17187 core: bump jsii from 1.114.1 to v1.115.0
  uv.lock
Labels: dependencies

#17189 core: bump microsoft-kiota-authentication-azure from 1.9.6 to v1.9.7
  uv.lock
Labels: dependencies

#17185 core: bump gevent from 25.8.2 to v25.9.1
  uv.lock
Labels: dependencies

#17179 core: bump anyio from 4.10.0 to v4.11.0
  uv.lock
Labels: dependencies

#17180 core: bump asgiref from 3.9.1 to v3.9.2
  uv.lock
Labels: dependencies

#17182 core: bump boto3 from 1.40.31 to v1.40.43
  uv.lock
Labels: dependencies

#16728 packages/django-dramatiq-postgres: fix error when updating task with no changes
  packages/django-dramatiq-postgres/django_dramatiq_postgres/middleware.py
Labels: backport/version-2025.8

#17237 tasks/middlewares/messages: make sure exceptions are always logged
  authentik/tasks/middleware.py
Labels: backport/version-2025.8

#17271 web/a11y: Flow inspector.
  web/src/common/styles/authentik.css
  web/src/common/styles/theme-dark.css
  web/src/flow/FlowExecutor.ts
  web/src/flow/FlowInspector.ts
  web/src/flow/FormStatic.ts
  web/src/flow/components/ak-brand-footer.ts
  web/src/flow/components/ak-flow-card.ts
Labels: a11y, area:frontend

#17278 web: Responsive toolbar flow
  web/src/admin/groups/MemberSelectModal.ts
  web/src/admin/property-mappings/PropertyMappingListPage.ts
  web/src/admin/users/UserListPage.ts
  web/src/common/styles/authentik.css
  web/src/elements/forms/ModalForm.ts
  web/src/elements/table/Table.ts
  web/src/elements/table/TablePage.ts
  web/src/elements/tasks/ScheduleList.ts
  web/src/elements/tasks/TaskList.ts
Labels: a11y, area:frontend

#17280 web: Minimal mobile flow
  web/src/common/global.ts
  web/src/common/styles/authentik.css
  web/src/flow/FlowExecutor.ts
  web/src/flow/FormStatic.ts
  web/src/flow/components/ak-flow-card.ts
Labels: area:frontend

#17311 web/a11y: User library
  web/src/user/LibraryApplication/index.ts
  web/src/user/LibraryPage/ak-library-application-list.ts
  web/src/user/LibraryPage/ak-library-application-search.ts
Labels: a11y, area:frontend

#17333 blueprints: ensure tasks retry on database errors
  authentik/blueprints/v1/tasks.py
Labels: backport/version-2025.8
