Repository goauthentik/authentik, pull requests merged in 2025-08, with the labels that each got.

#16003 web: Fix issue where `aria-owns` attribute triggers Chrome crash.
  web/src/elements/forms/FormGroup.ts
Labels: a11y

#16275 web: Fix hidden textarea `required` attribute. (cherry-pick #16168)
  web/src/admin/admin-settings/AdminSettingsForm.ts
  web/src/admin/crypto/CertificateKeyPairForm.ts
  web/src/admin/enterprise/EnterpriseLicenseForm.ts
  web/src/admin/sources/kerberos/KerberosSourceForm.ts
  web/src/admin/sources/oauth/OAuthSourceForm.ts
  web/src/elements/forms/Form.ts
Labels: bug, bug/confirmed

#16278 web: Fix issue where clicking a list item scrolls container (cherry-pick #16174)
  web/src/elements/ak-list-select/ak-list-select.ts
Labels: bug, bug/confirmed

#16277 web: Fix form group slots (cherry-pick #16276)
  web/src/admin/sources/oauth/OAuthSourceForm.ts
  web/src/admin/sources/plex/PlexSourceForm.ts
  web/src/admin/sources/saml/SAMLSourceForm.ts
Labels: bug, bug/confirmed

#16284 web: Username truncation, field alignment. (cherry-pick #16283)
  web/src/flow/FormStatic.ts
  web/src/flow/stages/authenticator_validate/AuthenticatorValidateStageCode.ts
  web/src/flow/stages/authenticator_validate/base.ts
  web/src/flow/stages/identification/IdentificationStage.ts
Labels: bug, bug/confirmed

#16014 web/e2e: Playwright end-to-end test runner
  web/.gitignore
  web/e2e/fixtures/FormFixture.ts
  web/e2e/fixtures/PageFixture.ts
  web/e2e/fixtures/PointerFixture.ts
  web/e2e/fixtures/SessionFixture.ts
  web/e2e/index.ts
  web/e2e/selectors/types.ts
  web/e2e/utils/generators.ts
  web/logger/node.js
  web/logger/transport.js
  web/package-lock.json
  web/package.json
  web/packages/core/environment/load/node.js
  web/packages/core/version/node.js
  web/playwright.config.js
  web/scripts/build-web.mjs
  web/src/admin/providers/ProviderWizard.ts
  web/src/common/theme.ts
  web/src/components/ak-field-errors.ts
  web/src/components/ak-wizard/WizardStep.ts
  web/src/components/ak-wizard/ak-wizard-steps.ts
  web/src/components/ak-wizard/types.ts
  web/src/elements/Interface.ts
  web/src/elements/LoadingOverlay.ts
  web/src/elements/forms/Form.ts
  web/src/elements/wizard/TypeCreateWizardPage.ts
  web/src/elements/wizard/Wizard.ts
  web/src/flow/stages/base.ts
  web/src/user/LibraryPage/ak-library-application-empty-list.ts
  web/src/user/LibraryPage/ak-library-impl.ts
  web/src/user/index.entrypoint.ts
  web/test/browser/providers.test.ts
  web/test/browser/session.test.ts
  web/test/lit/rendering.js
  web/test/lit/setup.js
  web/tests/pageobjects/login.page.ts
  web/tests/pageobjects/user-library.page.ts
  web/tests/specs/bad-logins-2.ts
  web/tests/specs/bad-logins.ts
  web/tests/specs/good-login.ts
  web/tests/tsconfig.json
  web/tests/wdio.conf.mjs
  web/tsconfig.build.json
  web/types/node.d.ts
  web/vite.config.js
  web/wdio.conf.mjs
Labels: enhancement

#16400 providers/rac: fix `AuthenticatedSession` migration
  authentik/providers/rac/migrations/0007_migrate_session.py
Labels: backport/version-2025.8, backport/version-2025.6, backport/version-2025.4

#16426 website/docs: rac public key: Fix typo
  website/docs/add-secure-apps/providers/rac/rac-public-key.md
Labels: backport/version-2025.8

#16446 core: bump h2 from 4.2.0 to 4.3.0
  uv.lock
Labels: backport/version-2025.8

#16466 website: Page redirect guide, documentation
  website/docs/developer-docs/docs/writing-documentation.md
Labels: backport/version-2025.8

#16442 website/docs: update how to rac and outpost landing page
  website/docs/add-secure-apps/outposts/index.mdx
  website/docs/add-secure-apps/providers/rac/how-to-rac.md
Labels: backport/version-2025.8

#16500 policies: remove object pk from authentik_policies_execution_time to reduce cardinality
  authentik/policies/apps.py
  authentik/policies/engine.py
  authentik/policies/process.py
Labels: backport/version-2025.8
